@startuml
class TcpEndpoint {
    - {static} <<readonly>> Lock : object
    - {static} _instance : TcpEndpoint?
    - TcpEndpoint()
    + {static} GetTcpEndpoint() : TcpEndpoint?
    + <<async>> StartAsync(cancellationToken:CancellationToken) : Task
    - <<async>> HandleClientAsync(client:TcpClient, cancellationToken:CancellationToken) : Task
    + StopAsync(cancellationToken:CancellationToken) : Task
}
TcpEndpoint --> "_tcpSocket" TcpListener
TcpEndpoint --> "_connectionRepository" ConnectionRepository
@enduml
