@startuml
class UserService {
    + UserService()
    + <<async>> OnUserInformationReceived(sender:object?, userEventArgs:UserEventArgs) : void
}
UserService --> "_userRepository" UserRepository
UserService --> "_connectionRepository" ConnectionRepository
@enduml
