@startuml
!include .\\App.xaml.puml
!include .\\AssemblyInfo.puml
!include .\\Models\Connection\ServerConnection.puml
!include .\\MVVM\Model\MessageReceiverModel.puml
!include .\\MVVM\View\MainWindow.xaml.puml
!include .\\MVVM\View\MessageInputView.xaml.puml
!include .\\MVVM\View\MessageReceiverView.xaml.puml
!include .\\MVVM\ViewModel\MessageInputViewModel.puml
!include .\\MVVM\ViewModel\MessageReceiverViewModel.puml
!include .\\MVVM\ViewModel\ViewModelLocator.puml
!include .\\Services\AuthenticationService\AuthenticationService.puml
!include .\\Services\ChatProtocolService\ChatProtocolService.puml
!include .\\Services\FileService\FileService.puml
!include .\\Services\ListenerService\ListenerService.puml
!include .\\Services\MessageService\MessageService.puml
!include .\\Services\NetworkService\NetworkService.puml
!include .\\obj\Debug\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0-windows\App.g.puml
!include .\\obj\Debug\net8.0-windows\App.g.i.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_25fmwyoq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_25fmwyoq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_beflnqdh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_beflnqdh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_dhctcva4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_dhctcva4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_ghp325rs_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_ghp325rs_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_pwk5tb0j_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_pwk5tb0j_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_qnekpkun_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client.Wpf_qnekpkun_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0gn5evup_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0gn5evup_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0odwft5a_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0odwft5a_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0ooqa5m5_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0ooqa5m5_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0skzb3ay_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0skzb3ay_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0sysdqlc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_0sysdqlc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_13xll0g4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_13xll0g4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_14vsdexh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_14vsdexh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_1z35of2j_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_1z35of2j_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_203iswwg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_203iswwg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_20cwmgt1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_20cwmgt1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_22ubaptj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_22ubaptj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_2gc4obq3_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_2gc4obq3_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_2o4ylquq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_2o4ylquq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3kza5bjf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3kza5bjf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3v10w5yt_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3v10w5yt_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3vyxtyym_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3vyxtyym_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3xbzv35d_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_3xbzv35d_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_45xxpgph_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_45xxpgph_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4e4pcxhj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4e4pcxhj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4eimhi3c_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4eimhi3c_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4feiysw2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4feiysw2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4ifieye5_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4ifieye5_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4nybeyj2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4nybeyj2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4q52shpf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4q52shpf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4qkbsbnj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4qkbsbnj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4xetdkpb_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4xetdkpb_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4zryte1j_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_4zryte1j_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5210yacr_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5210yacr_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_522i4w3y_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_522i4w3y_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5ceboi3z_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5ceboi3z_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5kgmmt4f_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5kgmmt4f_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5kynshkh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5kynshkh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5l43lbgw_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5l43lbgw_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5wdsdn5a_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_5wdsdn5a_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_a04bwnkj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_a04bwnkj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_aarp00vu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_aarp00vu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_bcz4luzw_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_bcz4luzw_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_bs4lgfro_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_bs4lgfro_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_c0tcwvdf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_c0tcwvdf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_c1r0oxct_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_c1r0oxct_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_c2z3mf2w_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_c2z3mf2w_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cfwxznd3_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cfwxznd3_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cnjm2fqb_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cnjm2fqb_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cra2dzxz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cra2dzxz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_crqkc0p0_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_crqkc0p0_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cuf30kh0_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cuf30kh0_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cyspucwc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_cyspucwc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_d2xwbvkh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_d2xwbvkh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_daooy1h4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_daooy1h4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dgj3fs35_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dgj3fs35_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dht20o1g_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dht20o1g_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dj5bqvl1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dj5bqvl1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dnbercrk_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dnbercrk_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dnkmpwzl_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dnkmpwzl_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dszxsnmo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dszxsnmo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dtaasjxx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dtaasjxx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dtktmcau_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_dtktmcau_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_e1kgagu1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_e1kgagu1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_e2cfutft_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_e2cfutft_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ebiwunaw_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ebiwunaw_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ee3xaar2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ee3xaar2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_eewu02yu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_eewu02yu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_eobqisuj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_eobqisuj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_esu3pewd_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_esu3pewd_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_evbyjsmg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_evbyjsmg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ewz25e4l_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ewz25e4l_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_fa0eg2do_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_fa0eg2do_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_flxc5cbt_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_flxc5cbt_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_foytgmfm_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_foytgmfm_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_fzgceaze_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_fzgceaze_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gijbbpyy_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gijbbpyy_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gnmplzbq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gnmplzbq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gpsx3yqs_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gpsx3yqs_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_grcl5gbn_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_grcl5gbn_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_grxui10e_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_grxui10e_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gvbxvnek_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gvbxvnek_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gy2ez2v4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_gy2ez2v4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_h00shbrt_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_h00shbrt_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_h1h3mcpf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_h1h3mcpf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hc23yto3_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hc23yto3_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hdspp1v0_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hdspp1v0_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_heem5kw2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_heem5kw2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hg3jvjsx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hg3jvjsx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hhb3wsog_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hhb3wsog_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hlmi1hsj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hlmi1hsj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hnbjhpsk_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hnbjhpsk_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hu14hch1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hu14hch1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hxcucgve_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hxcucgve_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hxlag5jf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_hxlag5jf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ienytwar_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ienytwar_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ihloxmja_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ihloxmja_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ij30uuiq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ij30uuiq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ikhazstb_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ikhazstb_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_inldp4g4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_inldp4g4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_isnngs5f_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_isnngs5f_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_iwn32oa1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_iwn32oa1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_j5co4dcs_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_j5co4dcs_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jee0vetz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jee0vetz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jqp2mzb1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jqp2mzb1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jrqfjcqr_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jrqfjcqr_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jtzrpkik_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jtzrpkik_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jxw31ojc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_jxw31ojc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_k3xo3h30_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_k3xo3h30_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_k4l0on5w_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_k4l0on5w_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kjf45ysp_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kjf45ysp_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kp33kwja_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kp33kwja_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kpccnnqe_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kpccnnqe_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ks0w3siz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ks0w3siz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kslztnbv_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_kslztnbv_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l2jxvak0_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l2jxvak0_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l2muf1hu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l2muf1hu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l45bxlnb_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l45bxlnb_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l5fzqxqz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_l5fzqxqz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lbtpzhyd_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lbtpzhyd_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lifp2wv4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lifp2wv4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lmiftq1y_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lmiftq1y_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lylhqzoi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_lylhqzoi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_m0io34sq_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_m0io34sq_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_m4d4ygji_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_m4d4ygji_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_msfvv5wu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_msfvv5wu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_mzrho2pe_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_mzrho2pe_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_n5khitx2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_n5khitx2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_nbc3ielb_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_nbc3ielb_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_nhrjecwp_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_nhrjecwp_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ni0ry1gi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ni0ry1gi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_npg312nd_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_npg312nd_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_nzxpy4pb_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_nzxpy4pb_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_onvc23o0_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_onvc23o0_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_p4bcok0i_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_p4bcok0i_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pcn0dyos_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pcn0dyos_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pgtfy4oi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pgtfy4oi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pq3jtlri_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pq3jtlri_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pz4vd431_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_pz4vd431_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_q1x2y05s_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_q1x2y05s_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_q2k1kn2g_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_q2k1kn2g_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qcpeujqc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qcpeujqc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qe5udhly_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qe5udhly_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qgr1dp3e_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qgr1dp3e_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qjeywxaj_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qjeywxaj_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qkr31vdd_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qkr31vdd_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qypahh5w_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_qypahh5w_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ra13rsj0_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ra13rsj0_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rkdeclcl_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rkdeclcl_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rodelhwc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rodelhwc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rycbhw55_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rycbhw55_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rzduofed_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_rzduofed_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_skb014v3_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_skb014v3_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_sln4415y_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_sln4415y_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_smj5cbrf_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_smj5cbrf_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_sqpqpazz_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_sqpqpazz_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_srgnvuc4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_srgnvuc4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_suiqjqi1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_suiqjqi1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_sujtq0i2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_sujtq0i2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t00unkgg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t00unkgg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t314qcjo_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t314qcjo_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t4sznvgi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t4sznvgi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t4xo3rar_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_t4xo3rar_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tchvbgve_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tchvbgve_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tcpqpv1o_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tcpqpv1o_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tgqs2rqs_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tgqs2rqs_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tigq3nig_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_tigq3nig_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ttl5qmar_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ttl5qmar_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_u4yjenoc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_u4yjenoc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ubkkbt4s_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ubkkbt4s_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ufpbgwax_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ufpbgwax_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_uvvwjbwc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_uvvwjbwc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_uvxks4cp_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_uvxks4cp_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_uzt0me35_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_uzt0me35_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vimif0uk_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vimif0uk_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vinr420r_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vinr420r_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vlbaffkh_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vlbaffkh_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vped3qij_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vped3qij_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vs0snz2u_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_vs0snz2u_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_w030iol4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_w030iol4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wbicc0gc_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wbicc0gc_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wf0n0due_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wf0n0due_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wjdxrl0l_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wjdxrl0l_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wtmsh1j1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wtmsh1j1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wup3vao1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wup3vao1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wzwwordb_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_wzwwordb_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_x2emwwv2_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_x2emwwv2_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xi2bobom_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xi2bobom_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xjmhnrj3_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xjmhnrj3_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xmqcfga4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xmqcfga4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xmqgwb2u_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_xmqgwb2u_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_y0vbtkk1_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_y0vbtkk1_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_y5vdxkg4_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_y5vdxkg4_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yijfrk1f_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yijfrk1f_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yimf3erg_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yimf3erg_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yjmiprye_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yjmiprye_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yoj4qruu_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yoj4qruu_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ypn5tl20_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ypn5tl20_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yq5z1ncm_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yq5z1ncm_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ytidq5dx_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ytidq5dx_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yvjrliyk_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_yvjrliyk_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ywrt4bsi_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ywrt4bsi_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zj4nlxkp_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zj4nlxkp_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zoabqxru_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zoabqxru_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ztp0e2vk_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_ztp0e2vk_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zx1x15fa_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zx1x15fa_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zx2d33ms_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zx2d33ms_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zy5rhyck_wpftmp.AssemblyInfo.puml
!include .\\obj\Debug\net8.0-windows\ChatApp.Client_zy5rhyck_wpftmp.GlobalUsings.g.puml
!include .\\obj\Debug\net8.0-windows\GeneratedInternalTypeHelper.g.puml
!include .\\obj\Debug\net8.0-windows\GeneratedInternalTypeHelper.g.i.puml
!include .\\obj\Debug\net8.0-windows\LoginControl.g.puml
!include .\\obj\Debug\net8.0-windows\LoginControl.g.i.puml
!include .\\obj\Debug\net8.0-windows\MainWindow.g.i.puml
!include .\\obj\Release\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Release\net8.0-windows\App.g.puml
!include .\\obj\Release\net8.0-windows\App.g.i.puml
!include .\\obj\Release\net8.0-windows\ChatApp.Client.AssemblyInfo.puml
!include .\\obj\Release\net8.0-windows\ChatApp.Client.GlobalUsings.g.puml
!include .\\obj\Release\net8.0-windows\MainWindow.g.puml
!include .\\obj\Release\net8.0-windows\MainWindow.g.i.puml
!include .\\obj\Debug\net8.0-windows\Controls\LoginControl.g.i.puml
!include .\\obj\Debug\net8.0-windows\Pages\login.g.i.puml
!include .\\obj\Debug\net8.0-windows\Pages\LoginPage.g.puml
!include .\\obj\Debug\net8.0-windows\Pages\LoginPage.g.i.puml
!include .\\obj\Debug\net8.0-windows\View\MainWindow.g.puml
!include .\\obj\Debug\net8.0-windows\View\MainWindow.g.i.puml
!include .\\obj\Debug\net8.0-windows\Views\LoginView.g.puml
!include .\\obj\Debug\net8.0-windows\Views\LoginView.g.i.puml
!include .\\obj\Release\net8.0-windows\win-x64\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Release\net8.0-windows\win-x64\App.g.puml
!include .\\obj\Release\net8.0-windows\win-x64\ChatApp.Client.Wpf.AssemblyInfo.puml
!include .\\obj\Release\net8.0-windows\win-x64\ChatApp.Client.Wpf.GlobalUsings.g.puml
!include .\\obj\Release\net8.0-windows\win-x64\MainWindow.g.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MainWindow.g.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MainWindow.g.i.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MessageInput.g.i.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MessageInputView.g.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MessageInputView.g.i.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MessageReceiverControl.g.i.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MessageReceiverView.g.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MessageReceiverView.g.i.puml
!include .\\obj\Debug\net8.0-windows\MVVM\View\MessageView.g.i.puml
!include .\\obj\Debug\net8.0-windows\Pages\Login\LoginPage.g.puml
!include .\\obj\Debug\net8.0-windows\Pages\Login\LoginPage.g.i.puml
@enduml
