@startuml
class MessageReceivedConformationEventArgs {
    + MessageReceivedConformationEventArgs(receivedMessage:MessageReceivedConfirmation)
}
MessageReceivedConformationEventArgs --> "ReceivedMessage" MessageReceivedConfirmation
@enduml
