@startuml
class MessageReceivedConformationEventArgs {
    + MessageReceivedConformationEventArgs(receivedMessage:MessageReceivedConfirmation)
}
EventArgs <|-- MessageReceivedConformationEventArgs
MessageReceivedConformationEventArgs --> "ReceivedMessage" MessageReceivedConfirmation
@enduml
