@startuml
class FileService {
    - {static} _instance : FileService?
    - {static} <<readonly>> Lock : object
    - FileService()
    + <<async>> SendFileAsync(fileInfo:FileInfo, senderUserId:Guid, targetUserId:Guid) : Task
}
FileService --> "Instance" FileService
@enduml
