@startuml
class ChatProtocolService {
    + ChatProtocolService(clientConnection:ClientConnection)
    + <<async>> WriteProtocolDataAsync(chatProtocolDataPackage:ChatProtocolDataPackage) : Task
    + <<async>> ReadProtocolDataAsync() : Task<ChatProtocolDataPackage>
}
ChatProtocolService --> "_clientConnection" ClientConnection
@enduml
